version: '2'
services:
  gatsby:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: gatsby-blog
    volumes:
      - ./src:/home/node/src
      - ./gatsby-config.js:/home/node/gatsby-config.js
      - ./public:/home/node/public
    ports:
      - "8000:8000"
    command: npm run develop
